trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self
  clean: true

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- bash: |
    echo ">>> Configure Git"
    git config --global user.name $(GIT_COMMITER_NAME)
    git config --global user.email $(GIT_COMMITER_EMAIL)
    git checkout -- .npmrc
    yarn version --patch
    echo ">>> Package"
    yarn package
    echo ">>> Publish"
    yarn deploy --packagePath $(find ./ -iname '*.vsix') --pat $(VSCODE_MARKETPLACE_TOKEN)
    echo ">>> Bump version"
    git push origin HEAD:master
  displayName: 'Package & publish'
  condition: succeeded()
  env:
    GIT_COMMITER_NAME: $(GIT_COMMITER_NAME)
    GIT_COMMITER_EMAIL: $(GIT_COMMITER_EMAIL)
    VSCODE_MARKETPLACE_TOKEN: $(VSCODE_MARKETPLACE_TOKEN)