trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'

- bash: |
    echo ">>> Publish"
    git clean -f
    yarn deploy -p $(VSCODE_MARKETPLACE_TOKEN)
  displayName: 'Publish'
  condition: succeeded()
  env:
    VSCODE_MARKETPLACE_TOKEN: $(VSCODE_MARKETPLACE_TOKEN)
