trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self
  clean: true

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Install Node dependencies'

- bash: |
    echo ">>> Publish"
    git config user.name $(GIT_COMMITER_NAME)
    git config user.email $(GIT_COMMITER_EMAIL)
    git checkout -- .npmrc
    yarn version --patch
    yarn package
    yarn deploy --packagePath $(find ./ -iname "*.vsix") --pat $(VSCODE_MARKETPLACE_TOKEN)
  displayName: 'Publish'
  condition: succeeded()
  env:
    GIT_COMMITER_NAME: $(GIT_COMMITER_NAME)
    GIT_COMMITER_EMAIL: $(GIT_COMMITER_EMAIL)
    VSCODE_MARKETPLACE_TOKEN: $(VSCODE_MARKETPLACE_TOKEN)